/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using EcoServerAPI.Client;
using EcoServerAPI.Api;
using EcoServerAPI.Model;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing AdminApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AdminApiTests
    {
        private AdminApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AdminApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AdminApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AdminApi
            //Assert.IsInstanceOfType(typeof(AdminApi), instance, "instance is a AdminApi");
        }

        
        /// <summary>
        /// Test AdminGetGetAccess
        /// </summary>
        [Test]
        public void AdminGetGetAccessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.AdminGetGetAccess(authtoken, authtokentype);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test AdminGetGetServerName
        /// </summary>
        [Test]
        public void AdminGetGetServerNameTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AdminGetGetServerName();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test AdminPostGameExport
        /// </summary>
        [Test]
        public void AdminPostGameExportTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //EcoWebServerWebModelsExportGameModel body = null;
            //var response = instance.AdminPostGameExport(authtoken, authtokentype, body);
            //Assert.IsInstanceOf<EcoWebServerWebModelsAdminReturnModel> (response, "response is EcoWebServerWebModelsAdminReturnModel");
        }
        
        /// <summary>
        /// Test AdminPostSetAccess
        /// </summary>
        [Test]
        public void AdminPostSetAccessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //string value = null;
            //string password = null;
            //instance.AdminPostSetAccess(authtoken, authtokentype, value, password);
            
        }
        
        /// <summary>
        /// Test AdminPostSetServerName
        /// </summary>
        [Test]
        public void AdminPostSetServerNameTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //string name = null;
            //instance.AdminPostSetServerName(authtoken, authtokentype, name);
            
        }
        
    }

}
