/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using EcoServerAPI.Client;
using EcoServerAPI.Api;
using EcoServerAPI.Model;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing LawApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class LawApiTests
    {
        private LawApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new LawApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LawApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LawApi
            //Assert.IsInstanceOfType(typeof(LawApi), instance, "instance is a LawApi");
        }

        
        /// <summary>
        /// Test LawGenerateTestData
        /// </summary>
        [Test]
        public void LawGenerateTestDataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //instance.LawGenerateTestData(authtoken, authtokentype);
            
        }
        
        /// <summary>
        /// Test LawGetDistrictMap
        /// </summary>
        [Test]
        public void LawGetDistrictMapTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.LawGetDistrictMap(name, authtoken, authtokentype);
            //Assert.IsInstanceOf<EcoWebServerDataTransferObjectsDistrictMapDTO> (response, "response is EcoWebServerDataTransferObjectsDistrictMapDTO");
        }
        
        /// <summary>
        /// Test LawGetLaw
        /// </summary>
        [Test]
        public void LawGetLawTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.LawGetLaw(id, authtoken, authtokentype);
            //Assert.IsInstanceOf<EcoWebServerDataTransferObjectsLawDTO> (response, "response is EcoWebServerDataTransferObjectsLawDTO");
        }
        
        /// <summary>
        /// Test LawList
        /// </summary>
        [Test]
        public void LawListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string states = null;
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.LawList(states, authtoken, authtokentype);
            //Assert.IsInstanceOf<List<EcoWebServerDataTransferObjectsLawDTO>> (response, "response is List<EcoWebServerDataTransferObjectsLawDTO>");
        }
        
        /// <summary>
        /// Test LawListAll
        /// </summary>
        [Test]
        public void LawListAllTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.LawListAll(authtoken, authtokentype);
            //Assert.IsInstanceOf<List<EcoWebServerDataTransferObjectsLawDTO>> (response, "response is List<EcoWebServerDataTransferObjectsLawDTO>");
        }
        
    }

}
