/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using EcoServerAPI.Client;
using EcoServerAPI.Api;
using EcoServerAPI.Model;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing ProfilingResultsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProfilingResultsApiTests
    {
        private ProfilingResultsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProfilingResultsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProfilingResultsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProfilingResultsApi
            //Assert.IsInstanceOfType(typeof(ProfilingResultsApi), instance, "instance is a ProfilingResultsApi");
        }

        
        /// <summary>
        /// Test ProfilingResultsDownload
        /// </summary>
        [Test]
        public void ProfilingResultsDownloadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string filename = null;
            //string authtoken = null;
            //string authtokentype = null;
            //instance.ProfilingResultsDownload(filename, authtoken, authtokentype);
            
        }
        
        /// <summary>
        /// Test ProfilingResultsList
        /// </summary>
        [Test]
        public void ProfilingResultsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.ProfilingResultsList(authtoken, authtokentype);
            //Assert.IsInstanceOf<List<EcoWebServerDataTransferObjectsProfilingResultDTO>> (response, "response is List<EcoWebServerDataTransferObjectsProfilingResultDTO>");
        }
        
    }

}
