/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using EcoServerAPI.Client;
using EcoServerAPI.Api;
using EcoServerAPI.Model;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing RootApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RootApiTests
    {
        private RootApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RootApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RootApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RootApi
            //Assert.IsInstanceOfType(typeof(RootApi), instance, "instance is a RootApi");
        }

        
        /// <summary>
        /// Test RootFrontPage
        /// </summary>
        [Test]
        public void RootFrontPageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.RootFrontPage(authtoken, authtokentype);
            //Assert.IsInstanceOf<EcoWebServerDataTransferObjectsFrontPage> (response, "response is EcoWebServerDataTransferObjectsFrontPage");
        }
        
        /// <summary>
        /// Test RootGetAdmins
        /// </summary>
        [Test]
        public void RootGetAdminsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.RootGetAdmins(authtoken, authtokentype);
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test RootGetInfo
        /// </summary>
        [Test]
        public void RootGetInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.RootGetInfo(authtoken, authtokentype);
            //Assert.IsInstanceOf<EcoSharedNetworkingServerInfo> (response, "response is EcoSharedNetworkingServerInfo");
        }
        
        /// <summary>
        /// Test RootIsAdmin
        /// </summary>
        [Test]
        public void RootIsAdminTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string authtoken = null;
            //string authtokentype = null;
            //var response = instance.RootIsAdmin(authtoken, authtokentype);
            //Assert.IsInstanceOf<bool?> (response, "response is bool?");
        }
        
    }

}
