/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = EcoServerAPI.Client.SwaggerDateConverter;

namespace EcoServerAPI.Model
{
    /// <summary>
    /// EcoStatsGraph
    /// </summary>
    [DataContract]
    public partial class EcoStatsGraph :  IEquatable<EcoStatsGraph>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EcoStatsGraph" /> class.
        /// </summary>
        /// <param name="keys">keys.</param>
        /// <param name="timeMin">timeMin.</param>
        /// <param name="timeMax">timeMax.</param>
        public EcoStatsGraph(List<EcoStatsKey> keys = default(List<EcoStatsKey>), double? timeMin = default(double?), double? timeMax = default(double?))
        {
            this.Keys = keys;
            this.TimeMin = timeMin;
            this.TimeMax = timeMax;
        }
        
        /// <summary>
        /// Gets or Sets Keys
        /// </summary>
        [DataMember(Name="keys", EmitDefaultValue=false)]
        public List<EcoStatsKey> Keys { get; set; }

        /// <summary>
        /// Gets or Sets TimeMin
        /// </summary>
        [DataMember(Name="timeMin", EmitDefaultValue=false)]
        public double? TimeMin { get; set; }

        /// <summary>
        /// Gets or Sets TimeMax
        /// </summary>
        [DataMember(Name="timeMax", EmitDefaultValue=false)]
        public double? TimeMax { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EcoStatsGraph {\n");
            sb.Append("  Keys: ").Append(Keys).Append("\n");
            sb.Append("  TimeMin: ").Append(TimeMin).Append("\n");
            sb.Append("  TimeMax: ").Append(TimeMax).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EcoStatsGraph);
        }

        /// <summary>
        /// Returns true if EcoStatsGraph instances are equal
        /// </summary>
        /// <param name="input">Instance of EcoStatsGraph to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EcoStatsGraph input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Keys == input.Keys ||
                    this.Keys != null &&
                    this.Keys.SequenceEqual(input.Keys)
                ) && 
                (
                    this.TimeMin == input.TimeMin ||
                    (this.TimeMin != null &&
                    this.TimeMin.Equals(input.TimeMin))
                ) && 
                (
                    this.TimeMax == input.TimeMax ||
                    (this.TimeMax != null &&
                    this.TimeMax.Equals(input.TimeMax))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Keys != null)
                    hashCode = hashCode * 59 + this.Keys.GetHashCode();
                if (this.TimeMin != null)
                    hashCode = hashCode * 59 + this.TimeMin.GetHashCode();
                if (this.TimeMax != null)
                    hashCode = hashCode * 59 + this.TimeMax.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
