/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = EcoServerAPI.Client.SwaggerDateConverter;

namespace EcoServerAPI.Model
{
    /// <summary>
    /// EcoWebServerWebModelsExportGameModel
    /// </summary>
    [DataContract]
    public partial class EcoWebServerWebModelsExportGameModel :  IEquatable<EcoWebServerWebModelsExportGameModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EcoWebServerWebModelsExportGameModel" /> class.
        /// </summary>
        /// <param name="s3ExportUri">s3ExportUri.</param>
        public EcoWebServerWebModelsExportGameModel(string s3ExportUri = default(string))
        {
            this.S3ExportUri = s3ExportUri;
        }
        
        /// <summary>
        /// Gets or Sets S3ExportUri
        /// </summary>
        [DataMember(Name="s3ExportUri", EmitDefaultValue=false)]
        public string S3ExportUri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class EcoWebServerWebModelsExportGameModel {\n");
            sb.Append("  S3ExportUri: ").Append(S3ExportUri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EcoWebServerWebModelsExportGameModel);
        }

        /// <summary>
        /// Returns true if EcoWebServerWebModelsExportGameModel instances are equal
        /// </summary>
        /// <param name="input">Instance of EcoWebServerWebModelsExportGameModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EcoWebServerWebModelsExportGameModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.S3ExportUri == input.S3ExportUri ||
                    (this.S3ExportUri != null &&
                    this.S3ExportUri.Equals(input.S3ExportUri))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.S3ExportUri != null)
                    hashCode = hashCode * 59 + this.S3ExportUri.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
