/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServer-API.Api;
using EcoServer-API.Model;
using EcoServer-API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServer-API.Test
{
    /// <summary>
    ///  Class for testing EcoSharedNetworkingServerInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoSharedNetworkingServerInfoTests
    {
        // TODO uncomment below to declare an instance variable for EcoSharedNetworkingServerInfo
        //private EcoSharedNetworkingServerInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoSharedNetworkingServerInfo
            //instance = new EcoSharedNetworkingServerInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoSharedNetworkingServerInfo
        /// </summary>
        [Test]
        public void EcoSharedNetworkingServerInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoSharedNetworkingServerInfo
            //Assert.IsInstanceOfType<EcoSharedNetworkingServerInfo> (instance, "variable 'instance' is a EcoSharedNetworkingServerInfo");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'External'
        /// </summary>
        [Test]
        public void ExternalTest()
        {
            // TODO unit test for the property 'External'
        }
        /// <summary>
        /// Test the property 'GamePort'
        /// </summary>
        [Test]
        public void GamePortTest()
        {
            // TODO unit test for the property 'GamePort'
        }
        /// <summary>
        /// Test the property 'WebPort'
        /// </summary>
        [Test]
        public void WebPortTest()
        {
            // TODO unit test for the property 'WebPort'
        }
        /// <summary>
        /// Test the property 'IsLAN'
        /// </summary>
        [Test]
        public void IsLANTest()
        {
            // TODO unit test for the property 'IsLAN'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DetailedDescription'
        /// </summary>
        [Test]
        public void DetailedDescriptionTest()
        {
            // TODO unit test for the property 'DetailedDescription'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'OnlinePlayers'
        /// </summary>
        [Test]
        public void OnlinePlayersTest()
        {
            // TODO unit test for the property 'OnlinePlayers'
        }
        /// <summary>
        /// Test the property 'TotalPlayers'
        /// </summary>
        [Test]
        public void TotalPlayersTest()
        {
            // TODO unit test for the property 'TotalPlayers'
        }
        /// <summary>
        /// Test the property 'OnlinePlayersNames'
        /// </summary>
        [Test]
        public void OnlinePlayersNamesTest()
        {
            // TODO unit test for the property 'OnlinePlayersNames'
        }
        /// <summary>
        /// Test the property 'AdminOnline'
        /// </summary>
        [Test]
        public void AdminOnlineTest()
        {
            // TODO unit test for the property 'AdminOnline'
        }
        /// <summary>
        /// Test the property 'TimeSinceStart'
        /// </summary>
        [Test]
        public void TimeSinceStartTest()
        {
            // TODO unit test for the property 'TimeSinceStart'
        }
        /// <summary>
        /// Test the property 'TimeLeft'
        /// </summary>
        [Test]
        public void TimeLeftTest()
        {
            // TODO unit test for the property 'TimeLeft'
        }
        /// <summary>
        /// Test the property 'Animals'
        /// </summary>
        [Test]
        public void AnimalsTest()
        {
            // TODO unit test for the property 'Animals'
        }
        /// <summary>
        /// Test the property 'Plants'
        /// </summary>
        [Test]
        public void PlantsTest()
        {
            // TODO unit test for the property 'Plants'
        }
        /// <summary>
        /// Test the property 'Laws'
        /// </summary>
        [Test]
        public void LawsTest()
        {
            // TODO unit test for the property 'Laws'
        }
        /// <summary>
        /// Test the property 'WorldSize'
        /// </summary>
        [Test]
        public void WorldSizeTest()
        {
            // TODO unit test for the property 'WorldSize'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'EconomyDesc'
        /// </summary>
        [Test]
        public void EconomyDescTest()
        {
            // TODO unit test for the property 'EconomyDesc'
        }
        /// <summary>
        /// Test the property 'SkillSpecialization'
        /// </summary>
        [Test]
        public void SkillSpecializationTest()
        {
            // TODO unit test for the property 'SkillSpecialization'
        }
        /// <summary>
        /// Test the property 'SkillSpecializationSetting'
        /// </summary>
        [Test]
        public void SkillSpecializationSettingTest()
        {
            // TODO unit test for the property 'SkillSpecializationSetting'
        }
        /// <summary>
        /// Test the property 'WorldObjective'
        /// </summary>
        [Test]
        public void WorldObjectiveTest()
        {
            // TODO unit test for the property 'WorldObjective'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'HasPassword'
        /// </summary>
        [Test]
        public void HasPasswordTest()
        {
            // TODO unit test for the property 'HasPassword'
        }
        /// <summary>
        /// Test the property 'HasMeteor'
        /// </summary>
        [Test]
        public void HasMeteorTest()
        {
            // TODO unit test for the property 'HasMeteor'
        }
        /// <summary>
        /// Test the property 'DistributionStationItems'
        /// </summary>
        [Test]
        public void DistributionStationItemsTest()
        {
            // TODO unit test for the property 'DistributionStationItems'
        }
        /// <summary>
        /// Test the property 'Playtimes'
        /// </summary>
        [Test]
        public void PlaytimesTest()
        {
            // TODO unit test for the property 'Playtimes'
        }
        /// <summary>
        /// Test the property 'DiscordAddress'
        /// </summary>
        [Test]
        public void DiscordAddressTest()
        {
            // TODO unit test for the property 'DiscordAddress'
        }
        /// <summary>
        /// Test the property 'IsPaused'
        /// </summary>
        [Test]
        public void IsPausedTest()
        {
            // TODO unit test for the property 'IsPaused'
        }
        /// <summary>
        /// Test the property 'ActiveAndOnlinePlayers'
        /// </summary>
        [Test]
        public void ActiveAndOnlinePlayersTest()
        {
            // TODO unit test for the property 'ActiveAndOnlinePlayers'
        }
        /// <summary>
        /// Test the property 'PeakActivePlayers'
        /// </summary>
        [Test]
        public void PeakActivePlayersTest()
        {
            // TODO unit test for the property 'PeakActivePlayers'
        }
        /// <summary>
        /// Test the property 'MaxActivePlayers'
        /// </summary>
        [Test]
        public void MaxActivePlayersTest()
        {
            // TODO unit test for the property 'MaxActivePlayers'
        }
        /// <summary>
        /// Test the property 'ExhaustionAfterHours'
        /// </summary>
        [Test]
        public void ExhaustionAfterHoursTest()
        {
            // TODO unit test for the property 'ExhaustionAfterHours'
        }
        /// <summary>
        /// Test the property 'IsLimitingHours'
        /// </summary>
        [Test]
        public void IsLimitingHoursTest()
        {
            // TODO unit test for the property 'IsLimitingHours'
        }
        /// <summary>
        /// Test the property 'ServerAchievements'
        /// </summary>
        [Test]
        public void ServerAchievementsTest()
        {
            // TODO unit test for the property 'ServerAchievements'
        }
        /// <summary>
        /// Test the property 'RelayAddress'
        /// </summary>
        [Test]
        public void RelayAddressTest()
        {
            // TODO unit test for the property 'RelayAddress'
        }
        /// <summary>
        /// Test the property 'Access'
        /// </summary>
        [Test]
        public void AccessTest()
        {
            // TODO unit test for the property 'Access'
        }
        /// <summary>
        /// Test the property 'JoinUrl'
        /// </summary>
        [Test]
        public void JoinUrlTest()
        {
            // TODO unit test for the property 'JoinUrl'
        }

    }

}
