/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServer-API.Api;
using EcoServer-API.Model;
using EcoServer-API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServer-API.Test
{
    /// <summary>
    ///  Class for testing EcoSharedNetworkingSkillSpecializationSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoSharedNetworkingSkillSpecializationSettingTests
    {
        // TODO uncomment below to declare an instance variable for EcoSharedNetworkingSkillSpecializationSetting
        //private EcoSharedNetworkingSkillSpecializationSetting instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoSharedNetworkingSkillSpecializationSetting
            //instance = new EcoSharedNetworkingSkillSpecializationSetting();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoSharedNetworkingSkillSpecializationSetting
        /// </summary>
        [Test]
        public void EcoSharedNetworkingSkillSpecializationSettingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoSharedNetworkingSkillSpecializationSetting
            //Assert.IsInstanceOfType<EcoSharedNetworkingSkillSpecializationSetting> (instance, "variable 'instance' is a EcoSharedNetworkingSkillSpecializationSetting");
        }



    }

}
