/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServer-API.Api;
using EcoServer-API.Model;
using EcoServer-API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServer-API.Test
{
    /// <summary>
    ///  Class for testing EcoWebServerDataTransferObjectsLawDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoWebServerDataTransferObjectsLawDTOTests
    {
        // TODO uncomment below to declare an instance variable for EcoWebServerDataTransferObjectsLawDTO
        //private EcoWebServerDataTransferObjectsLawDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoWebServerDataTransferObjectsLawDTO
            //instance = new EcoWebServerDataTransferObjectsLawDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoWebServerDataTransferObjectsLawDTO
        /// </summary>
        [Test]
        public void EcoWebServerDataTransferObjectsLawDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoWebServerDataTransferObjectsLawDTO
            //Assert.IsInstanceOfType<EcoWebServerDataTransferObjectsLawDTO> (instance, "variable 'instance' is a EcoWebServerDataTransferObjectsLawDTO");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UserDescription'
        /// </summary>
        [Test]
        public void UserDescriptionTest()
        {
            // TODO unit test for the property 'UserDescription'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Test]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
