/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServer-API.Api;
using EcoServer-API.Model;
using EcoServer-API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServer-API.Test
{
    /// <summary>
    ///  Class for testing EcoWebServerDataTransferObjectsElectedTitleDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoWebServerDataTransferObjectsElectedTitleDTOTests
    {
        // TODO uncomment below to declare an instance variable for EcoWebServerDataTransferObjectsElectedTitleDTO
        //private EcoWebServerDataTransferObjectsElectedTitleDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoWebServerDataTransferObjectsElectedTitleDTO
            //instance = new EcoWebServerDataTransferObjectsElectedTitleDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoWebServerDataTransferObjectsElectedTitleDTO
        /// </summary>
        [Test]
        public void EcoWebServerDataTransferObjectsElectedTitleDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoWebServerDataTransferObjectsElectedTitleDTO
            //Assert.IsInstanceOfType<EcoWebServerDataTransferObjectsElectedTitleDTO> (instance, "variable 'instance' is a EcoWebServerDataTransferObjectsElectedTitleDTO");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UserDescription'
        /// </summary>
        [Test]
        public void UserDescriptionTest()
        {
            // TODO unit test for the property 'UserDescription'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Test]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }
        /// <summary>
        /// Test the property 'OccupantNames'
        /// </summary>
        [Test]
        public void OccupantNamesTest()
        {
            // TODO unit test for the property 'OccupantNames'
        }

    }

}
