/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServer-API.Api;
using EcoServer-API.Model;
using EcoServer-API.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServer-API.Test
{
    /// <summary>
    ///  Class for testing EcoWebServerDataTransferObjectsElectionChoiceDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoWebServerDataTransferObjectsElectionChoiceDTOTests
    {
        // TODO uncomment below to declare an instance variable for EcoWebServerDataTransferObjectsElectionChoiceDTO
        //private EcoWebServerDataTransferObjectsElectionChoiceDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoWebServerDataTransferObjectsElectionChoiceDTO
            //instance = new EcoWebServerDataTransferObjectsElectionChoiceDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoWebServerDataTransferObjectsElectionChoiceDTO
        /// </summary>
        [Test]
        public void EcoWebServerDataTransferObjectsElectionChoiceDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoWebServerDataTransferObjectsElectionChoiceDTO
            //Assert.IsInstanceOfType<EcoWebServerDataTransferObjectsElectionChoiceDTO> (instance, "variable 'instance' is a EcoWebServerDataTransferObjectsElectionChoiceDTO");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Speech'
        /// </summary>
        [Test]
        public void SpeechTest()
        {
            // TODO unit test for the property 'Speech'
        }

    }

}
