/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoGameplayCivicsElectionsChoiceResults
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoGameplayCivicsElectionsChoiceResultsTests
    {
        // TODO uncomment below to declare an instance variable for EcoGameplayCivicsElectionsChoiceResults
        //private EcoGameplayCivicsElectionsChoiceResults instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoGameplayCivicsElectionsChoiceResults
            //instance = new EcoGameplayCivicsElectionsChoiceResults();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoGameplayCivicsElectionsChoiceResults
        /// </summary>
        [Test]
        public void EcoGameplayCivicsElectionsChoiceResultsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoGameplayCivicsElectionsChoiceResults
            //Assert.IsInstanceOfType<EcoGameplayCivicsElectionsChoiceResults> (instance, "variable 'instance' is a EcoGameplayCivicsElectionsChoiceResults");
        }


        /// <summary>
        /// Test the property 'ChoiceID'
        /// </summary>
        [Test]
        public void ChoiceIDTest()
        {
            // TODO unit test for the property 'ChoiceID'
        }
        /// <summary>
        /// Test the property 'MarkedUpName'
        /// </summary>
        [Test]
        public void MarkedUpNameTest()
        {
            // TODO unit test for the property 'MarkedUpName'
        }
        /// <summary>
        /// Test the property 'VotesPerRound'
        /// </summary>
        [Test]
        public void VotesPerRoundTest()
        {
            // TODO unit test for the property 'VotesPerRound'
        }
        /// <summary>
        /// Test the property 'Votes'
        /// </summary>
        [Test]
        public void VotesTest()
        {
            // TODO unit test for the property 'Votes'
        }
        /// <summary>
        /// Test the property 'SimpleResultVotes'
        /// </summary>
        [Test]
        public void SimpleResultVotesTest()
        {
            // TODO unit test for the property 'SimpleResultVotes'
        }

    }

}
