/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoSharedLocalizationLocString
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoSharedLocalizationLocStringTests
    {
        // TODO uncomment below to declare an instance variable for EcoSharedLocalizationLocString
        //private EcoSharedLocalizationLocString instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoSharedLocalizationLocString
            //instance = new EcoSharedLocalizationLocString();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoSharedLocalizationLocString
        /// </summary>
        [Test]
        public void EcoSharedLocalizationLocStringInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoSharedLocalizationLocString
            //Assert.IsInstanceOfType<EcoSharedLocalizationLocString> (instance, "variable 'instance' is a EcoSharedLocalizationLocString");
        }


        /// <summary>
        /// Test the property 'NotTranslated'
        /// </summary>
        [Test]
        public void NotTranslatedTest()
        {
            // TODO unit test for the property 'NotTranslated'
        }
        /// <summary>
        /// Test the property 'Inlinable'
        /// </summary>
        [Test]
        public void InlinableTest()
        {
            // TODO unit test for the property 'Inlinable'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }

    }

}
