/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoStatsKey
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoStatsKeyTests
    {
        // TODO uncomment below to declare an instance variable for EcoStatsKey
        //private EcoStatsKey instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoStatsKey
            //instance = new EcoStatsKey();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoStatsKey
        /// </summary>
        [Test]
        public void EcoStatsKeyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoStatsKey
            //Assert.IsInstanceOfType<EcoStatsKey> (instance, "variable 'instance' is a EcoStatsKey");
        }



    }

}
