/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoSharedMathVector3i
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoSharedMathVector3iTests
    {
        // TODO uncomment below to declare an instance variable for EcoSharedMathVector3i
        //private EcoSharedMathVector3i instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoSharedMathVector3i
            //instance = new EcoSharedMathVector3i();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoSharedMathVector3i
        /// </summary>
        [Test]
        public void EcoSharedMathVector3iInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoSharedMathVector3i
            //Assert.IsInstanceOfType<EcoSharedMathVector3i> (instance, "variable 'instance' is a EcoSharedMathVector3i");
        }


        /// <summary>
        /// Test the property 'X'
        /// </summary>
        [Test]
        public void XTest()
        {
            // TODO unit test for the property 'X'
        }
        /// <summary>
        /// Test the property 'Y'
        /// </summary>
        [Test]
        public void YTest()
        {
            // TODO unit test for the property 'Y'
        }
        /// <summary>
        /// Test the property 'Z'
        /// </summary>
        [Test]
        public void ZTest()
        {
            // TODO unit test for the property 'Z'
        }
        /// <summary>
        /// Test the property 'Magnitude'
        /// </summary>
        [Test]
        public void MagnitudeTest()
        {
            // TODO unit test for the property 'Magnitude'
        }
        /// <summary>
        /// Test the property 'SqrMagnitude'
        /// </summary>
        [Test]
        public void SqrMagnitudeTest()
        {
            // TODO unit test for the property 'SqrMagnitude'
        }
        /// <summary>
        /// Test the property 'MultTogether'
        /// </summary>
        [Test]
        public void MultTogetherTest()
        {
            // TODO unit test for the property 'MultTogether'
        }
        /// <summary>
        /// Test the property 'Xz'
        /// </summary>
        [Test]
        public void XzTest()
        {
            // TODO unit test for the property 'Xz'
        }
        /// <summary>
        /// Test the property 'XzFullNeighborsAndSelf'
        /// </summary>
        [Test]
        public void XzFullNeighborsAndSelfTest()
        {
            // TODO unit test for the property 'XzFullNeighborsAndSelf'
        }
        /// <summary>
        /// Test the property 'XzNeighborsAndSelf'
        /// </summary>
        [Test]
        public void XzNeighborsAndSelfTest()
        {
            // TODO unit test for the property 'XzNeighborsAndSelf'
        }
        /// <summary>
        /// Test the property 'XzNeighborsAndDir'
        /// </summary>
        [Test]
        public void XzNeighborsAndDirTest()
        {
            // TODO unit test for the property 'XzNeighborsAndDir'
        }
        /// <summary>
        /// Test the property 'XzNeighbors'
        /// </summary>
        [Test]
        public void XzNeighborsTest()
        {
            // TODO unit test for the property 'XzNeighbors'
        }
        /// <summary>
        /// Test the property 'XzFullNeighbors'
        /// </summary>
        [Test]
        public void XzFullNeighborsTest()
        {
            // TODO unit test for the property 'XzFullNeighbors'
        }
        /// <summary>
        /// Test the property 'XyzNeighborsAndSelf'
        /// </summary>
        [Test]
        public void XyzNeighborsAndSelfTest()
        {
            // TODO unit test for the property 'XyzNeighborsAndSelf'
        }
        /// <summary>
        /// Test the property 'XyzNeighbors'
        /// </summary>
        [Test]
        public void XyzNeighborsTest()
        {
            // TODO unit test for the property 'XyzNeighbors'
        }
        /// <summary>
        /// Test the property 'Full26Neighbors'
        /// </summary>
        [Test]
        public void Full26NeighborsTest()
        {
            // TODO unit test for the property 'Full26Neighbors'
        }
        /// <summary>
        /// Test the property 'Normalized'
        /// </summary>
        [Test]
        public void NormalizedTest()
        {
            // TODO unit test for the property 'Normalized'
        }
        /// <summary>
        /// Test the property 'NormalizedOrZero'
        /// </summary>
        [Test]
        public void NormalizedOrZeroTest()
        {
            // TODO unit test for the property 'NormalizedOrZero'
        }

    }

}
