/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoStatsGraph
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoStatsGraphTests
    {
        // TODO uncomment below to declare an instance variable for EcoStatsGraph
        //private EcoStatsGraph instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoStatsGraph
            //instance = new EcoStatsGraph();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoStatsGraph
        /// </summary>
        [Test]
        public void EcoStatsGraphInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoStatsGraph
            //Assert.IsInstanceOfType<EcoStatsGraph> (instance, "variable 'instance' is a EcoStatsGraph");
        }


        /// <summary>
        /// Test the property 'Keys'
        /// </summary>
        [Test]
        public void KeysTest()
        {
            // TODO unit test for the property 'Keys'
        }
        /// <summary>
        /// Test the property 'TimeMin'
        /// </summary>
        [Test]
        public void TimeMinTest()
        {
            // TODO unit test for the property 'TimeMin'
        }
        /// <summary>
        /// Test the property 'TimeMax'
        /// </summary>
        [Test]
        public void TimeMaxTest()
        {
            // TODO unit test for the property 'TimeMax'
        }

    }

}
