/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoSharedMathRay
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoSharedMathRayTests
    {
        // TODO uncomment below to declare an instance variable for EcoSharedMathRay
        //private EcoSharedMathRay instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoSharedMathRay
            //instance = new EcoSharedMathRay();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoSharedMathRay
        /// </summary>
        [Test]
        public void EcoSharedMathRayInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoSharedMathRay
            //Assert.IsInstanceOfType<EcoSharedMathRay> (instance, "variable 'instance' is a EcoSharedMathRay");
        }


        /// <summary>
        /// Test the property 'FirstPos'
        /// </summary>
        [Test]
        public void FirstPosTest()
        {
            // TODO unit test for the property 'FirstPos'
        }
        /// <summary>
        /// Test the property 'FirstRay'
        /// </summary>
        [Test]
        public void FirstRayTest()
        {
            // TODO unit test for the property 'FirstRay'
        }

    }

}
