/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoWebServerDataTransferObjectsCivicActionDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoWebServerDataTransferObjectsCivicActionDTOTests
    {
        // TODO uncomment below to declare an instance variable for EcoWebServerDataTransferObjectsCivicActionDTO
        //private EcoWebServerDataTransferObjectsCivicActionDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoWebServerDataTransferObjectsCivicActionDTO
            //instance = new EcoWebServerDataTransferObjectsCivicActionDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoWebServerDataTransferObjectsCivicActionDTO
        /// </summary>
        [Test]
        public void EcoWebServerDataTransferObjectsCivicActionDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoWebServerDataTransferObjectsCivicActionDTO
            //Assert.IsInstanceOfType<EcoWebServerDataTransferObjectsCivicActionDTO> (instance, "variable 'instance' is a EcoWebServerDataTransferObjectsCivicActionDTO");
        }


        /// <summary>
        /// Test the property 'ActionOnComplete'
        /// </summary>
        [Test]
        public void ActionOnCompleteTest()
        {
            // TODO unit test for the property 'ActionOnComplete'
        }
        /// <summary>
        /// Test the property 'ActionOnCompleteTableHeader'
        /// </summary>
        [Test]
        public void ActionOnCompleteTableHeaderTest()
        {
            // TODO unit test for the property 'ActionOnCompleteTableHeader'
        }
        /// <summary>
        /// Test the property 'ActionOnCompleteTable'
        /// </summary>
        [Test]
        public void ActionOnCompleteTableTest()
        {
            // TODO unit test for the property 'ActionOnCompleteTable'
        }
        /// <summary>
        /// Test the property 'ActionOnCompleteFullDescription'
        /// </summary>
        [Test]
        public void ActionOnCompleteFullDescriptionTest()
        {
            // TODO unit test for the property 'ActionOnCompleteFullDescription'
        }
        /// <summary>
        /// Test the property 'DistrictMapBefore'
        /// </summary>
        [Test]
        public void DistrictMapBeforeTest()
        {
            // TODO unit test for the property 'DistrictMapBefore'
        }
        /// <summary>
        /// Test the property 'DistrictMapAfter'
        /// </summary>
        [Test]
        public void DistrictMapAfterTest()
        {
            // TODO unit test for the property 'DistrictMapAfter'
        }

    }

}
