/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoWebServerDataTransferObjectsElectionDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoWebServerDataTransferObjectsElectionDTOTests
    {
        // TODO uncomment below to declare an instance variable for EcoWebServerDataTransferObjectsElectionDTO
        //private EcoWebServerDataTransferObjectsElectionDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoWebServerDataTransferObjectsElectionDTO
            //instance = new EcoWebServerDataTransferObjectsElectionDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoWebServerDataTransferObjectsElectionDTO
        /// </summary>
        [Test]
        public void EcoWebServerDataTransferObjectsElectionDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoWebServerDataTransferObjectsElectionDTO
            //Assert.IsInstanceOfType<EcoWebServerDataTransferObjectsElectionDTO> (instance, "variable 'instance' is a EcoWebServerDataTransferObjectsElectionDTO");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UserDescription'
        /// </summary>
        [Test]
        public void UserDescriptionTest()
        {
            // TODO unit test for the property 'UserDescription'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Creator'
        /// </summary>
        [Test]
        public void CreatorTest()
        {
            // TODO unit test for the property 'Creator'
        }
        /// <summary>
        /// Test the property 'Choices'
        /// </summary>
        [Test]
        public void ChoicesTest()
        {
            // TODO unit test for the property 'Choices'
        }
        /// <summary>
        /// Test the property 'TotalVotes'
        /// </summary>
        [Test]
        public void TotalVotesTest()
        {
            // TODO unit test for the property 'TotalVotes'
        }
        /// <summary>
        /// Test the property 'TimeEnd'
        /// </summary>
        [Test]
        public void TimeEndTest()
        {
            // TODO unit test for the property 'TimeEnd'
        }
        /// <summary>
        /// Test the property 'TimeEndAgo'
        /// </summary>
        [Test]
        public void TimeEndAgoTest()
        {
            // TODO unit test for the property 'TimeEndAgo'
        }
        /// <summary>
        /// Test the property 'TimeStart'
        /// </summary>
        [Test]
        public void TimeStartTest()
        {
            // TODO unit test for the property 'TimeStart'
        }
        /// <summary>
        /// Test the property 'TimeStartAgo'
        /// </summary>
        [Test]
        public void TimeStartAgoTest()
        {
            // TODO unit test for the property 'TimeStartAgo'
        }
        /// <summary>
        /// Test the property 'Finished'
        /// </summary>
        [Test]
        public void FinishedTest()
        {
            // TODO unit test for the property 'Finished'
        }
        /// <summary>
        /// Test the property 'Passed'
        /// </summary>
        [Test]
        public void PassedTest()
        {
            // TODO unit test for the property 'Passed'
        }
        /// <summary>
        /// Test the property 'PendingVote'
        /// </summary>
        [Test]
        public void PendingVoteTest()
        {
            // TODO unit test for the property 'PendingVote'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'Provisions'
        /// </summary>
        [Test]
        public void ProvisionsTest()
        {
            // TODO unit test for the property 'Provisions'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'ElectionProcess'
        /// </summary>
        [Test]
        public void ElectionProcessTest()
        {
            // TODO unit test for the property 'ElectionProcess'
        }
        /// <summary>
        /// Test the property 'PositionForWinner'
        /// </summary>
        [Test]
        public void PositionForWinnerTest()
        {
            // TODO unit test for the property 'PositionForWinner'
        }
        /// <summary>
        /// Test the property 'BooleanElection'
        /// </summary>
        [Test]
        public void BooleanElectionTest()
        {
            // TODO unit test for the property 'BooleanElection'
        }
        /// <summary>
        /// Test the property 'ElectionDescription'
        /// </summary>
        [Test]
        public void ElectionDescriptionTest()
        {
            // TODO unit test for the property 'ElectionDescription'
        }

    }

}
