/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTOTests
    {
        // TODO uncomment below to declare an instance variable for EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTO
        //private EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTO
            //instance = new EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTO
        /// </summary>
        [Test]
        public void EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTO
            //Assert.IsInstanceOfType<EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTO> (instance, "variable 'instance' is a EcoWebServerDataTransferObjectsWorldLayersWorldLayerDTO");
        }


        /// <summary>
        /// Test the property 'LayerName'
        /// </summary>
        [Test]
        public void LayerNameTest()
        {
            // TODO unit test for the property 'LayerName'
        }
        /// <summary>
        /// Test the property 'LayerDisplayName'
        /// </summary>
        [Test]
        public void LayerDisplayNameTest()
        {
            // TODO unit test for the property 'LayerDisplayName'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Tooltip'
        /// </summary>
        [Test]
        public void TooltipTest()
        {
            // TODO unit test for the property 'Tooltip'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'DisplayRow'
        /// </summary>
        [Test]
        public void DisplayRowTest()
        {
            // TODO unit test for the property 'DisplayRow'
        }

    }

}
