/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoWebServerDataTransferObjectsUserDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoWebServerDataTransferObjectsUserDTOTests
    {
        // TODO uncomment below to declare an instance variable for EcoWebServerDataTransferObjectsUserDTO
        //private EcoWebServerDataTransferObjectsUserDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoWebServerDataTransferObjectsUserDTO
            //instance = new EcoWebServerDataTransferObjectsUserDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoWebServerDataTransferObjectsUserDTO
        /// </summary>
        [Test]
        public void EcoWebServerDataTransferObjectsUserDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoWebServerDataTransferObjectsUserDTO
            //Assert.IsInstanceOfType<EcoWebServerDataTransferObjectsUserDTO> (instance, "variable 'instance' is a EcoWebServerDataTransferObjectsUserDTO");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SlgId'
        /// </summary>
        [Test]
        public void SlgIdTest()
        {
            // TODO unit test for the property 'SlgId'
        }
        /// <summary>
        /// Test the property 'SteamId'
        /// </summary>
        [Test]
        public void SteamIdTest()
        {
            // TODO unit test for the property 'SteamId'
        }

    }

}
