/* 
 * Eco Game API
 *
 * First API draft for Eco. Heavy work in progress and subject to changes.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EcoServerAPI.Api;
using EcoServerAPI.Model;
using EcoServerAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EcoServerAPI.Test
{
    /// <summary>
    ///  Class for testing EcoWebServerDataTransferObjectsElectionResultsDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EcoWebServerDataTransferObjectsElectionResultsDTOTests
    {
        // TODO uncomment below to declare an instance variable for EcoWebServerDataTransferObjectsElectionResultsDTO
        //private EcoWebServerDataTransferObjectsElectionResultsDTO instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcoWebServerDataTransferObjectsElectionResultsDTO
            //instance = new EcoWebServerDataTransferObjectsElectionResultsDTO();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcoWebServerDataTransferObjectsElectionResultsDTO
        /// </summary>
        [Test]
        public void EcoWebServerDataTransferObjectsElectionResultsDTOInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EcoWebServerDataTransferObjectsElectionResultsDTO
            //Assert.IsInstanceOfType<EcoWebServerDataTransferObjectsElectionResultsDTO> (instance, "variable 'instance' is a EcoWebServerDataTransferObjectsElectionResultsDTO");
        }


        /// <summary>
        /// Test the property 'ChoiceRanks'
        /// </summary>
        [Test]
        public void ChoiceRanksTest()
        {
            // TODO unit test for the property 'ChoiceRanks'
        }
        /// <summary>
        /// Test the property 'TotalVotesForWinner'
        /// </summary>
        [Test]
        public void TotalVotesForWinnerTest()
        {
            // TODO unit test for the property 'TotalVotesForWinner'
        }
        /// <summary>
        /// Test the property 'Winners'
        /// </summary>
        [Test]
        public void WinnersTest()
        {
            // TODO unit test for the property 'Winners'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'Finished'
        /// </summary>
        [Test]
        public void FinishedTest()
        {
            // TODO unit test for the property 'Finished'
        }

    }

}
